# Generated by Django 4.0 on 2022-04-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='Contact',
        ),
    ]
