# Generated by Django 4.0 on 2022-04-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_email_contact_emal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emal',
            new_name='exampleInputEmail1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='passw',
            new_name='exampleInputPassword1',
        ),
    ]
