# Generated by Django 4.0 on 2022-04-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_emal_contact_exampleinputemail1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='exampleInputPassword1',
            new_name='pass2',
        ),
    ]
